### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by jgillard** [hakancelik96/unimport#150]
Now that #147 has been released I tried upgrading from 0.3.0 to 0.6.8. I noticed that it was running slower so I did a few timed runs on the latest 3 versions. I installed each version from pip, and ran the command `time unimport apps` for each 3 times.

Release 0.3.0: 2.80 secs, 2.53 secs, 2.82 secs. **Avg: 2.72 secs**.
Release 0.6.6: 4.24 secs, 4.20 secs, 4.40 secs. **Avg: 4.28 secs (+57%)**.
Release 0.6.8: 4.71 secs, 4.63 secs, 4.80 secs. **Avg: 4.71 secs (+73%)**.

The performance is far worse through pre-commit which I want to be able to use. I ran the command `time pre-commit run unimport --all-files`

Release 0.3.0: 16.04 secs, 17.67 secs, 18.72 secs. **Avg: 17.48 secs**.
Release 0.6.6: 30.03 secs, 30.76 secs, 28.81 secs. **Avg: 29.87 secs (+71%)**.
Release 0.6.8: 29.90 secs, 30.28 secs, 30.40 secs. **Avg: 30.19 secs (+73%)**.

Both sets of tests show a large slowdown between 0.3.0 and 0.6.x.
I really want to be able to use this tool, but pre-commit in particular here is too slow for me.

**Comment by isidentical** [comment]
One thing that I noticed while catching up on the new patches (was away for a while) is the usage of `ast.get_source_segment` in every import statement;
https://github.com/hakancelik96/unimport/blob/abc766a40a62173415884fe5c81b6503257f67d4/unimport/scan.py#L296-L301
(for checking out whether it is ignored or not). 

The function itself, is alright, just a bunch of checks and slicing. But the real problem comes from `ast._splitlines_no_ff` which is kind of inefficient since it is much like a `splitlines()` call but it tries to imitate the python parser's splitting behavior (will look into it, to maybe optimize in the core). 

What I could say is, it is much more simple and *effective* to have a structure like `Module(.., TypeIgnore* type_ignores)` and calculate them beforehand instead of calling this function every time and import statement is seen. 

But if you want a really short cut, NOT ADVISED, the results of this function can be cached `ast._splitlines_no_ff = functools.lru_cache(...)(ast._splitlines_no_ff)` which from what I initially observed boosts the performance up to %100! 

Without cache: https://gist.githubusercontent.com/isidentical/2957bcae4a7921fff2a32355878fda5a/raw/85075b7029f9bdbe3509dc9128ca625551704ca9/initial.out
With cache: https://gist.githubusercontent.com/isidentical/2957bcae4a7921fff2a32355878fda5a/raw/85075b7029f9bdbe3509dc9128ca625551704ca9/secondary.out

If implemented correctly (just like `type_ignores`) I believe this can achieve much more!

**Comment by isidentical** [comment]
Also, there are many more 'nit' points that can be concluded by looking at the profiler output but just doing this would be one of the best start, IMHO.

**Comment by isik-kaplan** [comment]
What's the reason behind the capital "not advised"? Is it the prior suggestion?

**Comment by isidentical** [comment]
> What's the reason behind the capital "not advised"? Is it the prior suggestion?

No, just putting a `lru_cache()` to an internal function at top of the file, isn't the real way of doing this (even though it boosts the performance %100+ly). That is why I clearly stated the intention of the code that I pasted there, but the real way of doing this is explained in my previous message (type_ignores-like-system, ahead-of-time)

**Comment by isik-kaplan** [comment]
> explained in my previous message

I meant prior as in, by order; not by importance. So your suggestion is this(right?): 

> What I could say is, it is much more simple and effective to have a structure like Module(.., TypeIgnore* type_ignores) and calculate them beforehand instead of calling this function every time and import statement is seen. 

I'm not really experienced when it comes to static analysis, so just wanted to learn your reasoning. Thanks.

**Comment by hakancelik96** [comment]
Thank you, I'll be working over the weekend on this issue.
