### ISSUE TITLE
Incorrect results on bigger projects

### ISSUE THREAD

**Issue by isik-kaplan** [hakancelik96/unimport#168]
Hello! I'm trying to use unimport with couple of both my-personal projects and some work related products we have in-house. (Actually, more than a couple, both day-job and customers whom I do consultancy have their own codebases). 

For my personal projects it seems to work real well, but whenever I'm trying to introduce the unimport to bigger codebases than mine, it just halts the project, half of the test cases starts to fail, etc...

Not really going to ask you to investigate all of them, obviously. But can you at least put couple of big python codebases to testing pipeline so we can get a rough idea how consistent unimport works? 

Couple of ideas: CPython, Twisted, Tornado, Zope, Django

Seeing these pass would make me question my codebase, but seeing that the tests that pass without unimport failing right after makes me think there could be some bugs left undiagnosed.

Now that I think of it, one of the biggest problems I assume are the `__init__.py` imports, no one in the wild west before added the init imports to `__all__`, it could come handy to make it optional for old folks like me to adapt easier.

**Comment by hakancelik96** [comment]
There are currently two known Unimport cases that do not have support yet.

for example.

```python
if True:
    import x
else:
    import x
```
```python
import x

def f ():
     import x
     return x

print (x)
```

Unimport detects these two situations wrong because
1. If, elif, else statement analysis isn't done in Unimport yet.
2. Scope analysis isn't done in Unimport yet.

If you have these situations in your codebase, we recommend using ` # unimport: skip` or ` # unimport: skip_file ` comment and if you don't want ` __init__ `  files to be scanned, you can use the `--exclude` flag, this issue has been discussed before and we decided not to add a flag like `--ignore-init`.

**Comment by isik-kaplan** [comment]
> this issue has been discussed before and we decided not to add a flag like --ignore-init.

Can you link the issue if it is somewhere public? Thanks!
