### ISSUE TITLE
LF is converted to CRLF on windows

### ISSUE THREAD

**Issue by Trim21** [hakancelik96/unimport#183]

**Comment by hakancelik96** [comment]
Could you give more details? I don't understand anything.

**Comment by CAM-Gerlach** [comment]
@hakancelik96 Was about to report this myself. Unimport does not respect the EOL of the passed in files, and instead arbitrarily converts any modified source files to whatever convention the particular platform it is running on uses. I'm not aware of a case where that would be the desirable behavior, whereas many projects standardize on one newline convention (typically `\n`) for all source files, which this breaks. To repro, simply create a Python file with an unused import, save it in an EoL convention that doesn't happen to be your particular platform's default, and run unimport on the file with the `--remove` flag.

To solve this, you just need to check the EoL convention when reading in the file, and pass that explicitly on writing it. For example, since you already have nice read and write helpers set up, you can just add `newlines = stream.newlines` [in utils.read()](https://github.com/hakancelik96/unimport/blob/2875c033c00877b6797f3a05761c7c7fe9aae46c/unimport/utils.py#L127) right after you get the encoding, and then return it as the third element of the tuple (returning `None` on error, which is the default platform-specific behavior), and store it in a variable in your `main` function, like you do the other two. Then, you'll need to pass it when writing the file; `pathlib.Path.write()` [only gained support for passing `newlines` in Python 3.10](https://bugs.python.org/issue23706), so you'll either need to use `with open(py_path, "w", encoding=encoding, newline=newline) as py_file: py_file.write(refactor_result)` or write another small wrapper function in `utils` like for `read` and call that.

Happy to submit a PR if you prefer; if so, let me know which of the latter two approaches you'd like me to take.

**Comment by hakancelik96** [comment]
You caught it very well, congratulations. It was a subject that I did not know, I learned it thanks to you. I would certainly be very pleased, if you could solve the problem you found yourself by PR. and I think your first approach would be more appropriate.

**Comment by CAM-Gerlach** [comment]
@hakancelik96 Okay, thanks; in work. While the change itself is fairly straightforward, I'll admit I'm not terribly familiar with the conventions of the legacy `unittest`, as I've only really worked with Pytest at least on serious projects, but I'll give it a shot. I'm also not sure whether and/or how you want a changelog entry to be done, given your changelog's non-standard format, so any guidance on that would be appreciated.
