### ISSUE TITLE
Version 0.2.7 disappeared from PyPi

### ISSUE THREAD

**Issue by askmon** [hakancelik96/unimport#78]
We just realised the version 0.2.7 disappeared from PyPi , breaking some of our builds. Is there any reason for the removal or was it an accident? (I'm kinda new to the python world so I really don't know if it's a common practice)

Tks!

**Comment by hakancelik96** [comment]
Hello, thanks for the good question.

I deleted all of the old versions from the PyPI because after I released a new version when I looked at the download rates, I saw that the old versions were still being downloaded ( more than the new version ), I decided to release only the versions I recommend to avoid the use of bad scanning, bad refactoring, and lots of bugs.

The version I recommend now is 0.2.8.

- Compatible with older versions
- There are fewer bugs
- There are new features

## Why should I not use an older version.

The new version is compatible with the old versions, nothing has affected you, new features have been added, the bugs found have been fixed, so I strongly recommend the use of the latest version, if there is a situation that prevents you from using the new version, please open the issue I will fix it soon for you.

**Comment by isidentical** [comment]
I am so sorry for what happened to you, I am well aware that wasn't the action he actually supposed to do. We won't ever delete the old versions, at worts we will yank them (unsure about that process, if we ever need it or not). Thank you so much for making me aware of this situation. 

As I said, please try to update the unimport to the `0.2.8` version and then we'll make sure that versions never going to disappear (unless some of the crew takes action by themselves). Closing bug since we can not resolve this issue furtherly.
